services:
    backend:
      build:
        context: ./Backend
      container_name: symfony_app
      restart: unless-stopped
      working_dir: /var/www/html
      volumes:
        - ./backend:/var/www/html
      depends_on:
        - database
      networks:
        - app_network

    nginx:
      image: nginx:latest
      container_name: nginx_server
      restart: unless-stopped
      ports:
        - "9000:9000"
      volumes:
        - ./Backend:/var/www/html
        - ./Backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - backend
      networks:
        - app_network
    frontend:
      build:
        context: ./Frontend
      container_name: angular_app
      restart: unless-stopped
      ports:
        - "4200:4200"
      depends_on:
        - backend
      networks:
        - app_network

volumes:
  db_data:

networks:
  app_network: