# we wil use this docker-compose file to run our symfony and angular app in two docker containers
services:
    backend:
      build:
        context: ./Backend
      container_name: symfony_app
      restart: always
      working_dir: /var/www/html
      volumes:
        - ./Backend:/var/www/html
      networks:
        - app_network

    #we will use and nginx server to serve our symfony app, we will access it in localhost:9000
    nginx:
      image: nginx:latest
      container_name: nginx_server
      restart: unless-stopped
      ports:
        - "9000:80"
      volumes:
        - ./Backend:/var/www/html
        - ./Backend/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - backend
      networks:
        - app_network

    #the frontend will be served by an angular server, we will access it in localhost:8080
    frontend:
      build:
        context: ./Frontend
      container_name: angular_app
      restart: unless-stopped
      ports:
        - "8080:80"
      depends_on:
        - nginx
      networks:
        - app_network

    database:
      image: mysql:8
      container_name: symfony_database
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: symfony
        MYSQL_USER: symfony
        MYSQL_PASSWORD: symfony
      ports:
        - "3306:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      networks:
        - app_network

volumes:
  mysql_data: 

networks:
  app_network:
    driver: bridge