version: '3.8'

services:
  symfony_app:
    build: .
    container_name: symfony_app
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  web:
    image: nginx:alpine
    container_name: symfony_nginx
    restart: always
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - symfony_app
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    container_name: symfony_db
    restart: always
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony_user
      POSTGRES_PASSWORD: symfony_pass
    ports:
      - "5432:5432"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

